### ISSUE TITLE
Error: Executable does not have proper permissions

### ISSUE THREAD

**Issue by TiasaGhosh** [OpenFAST/r-test#28]
Hello everybody!
I am new to OpenFAST and have been trying to run some regression tests. I am using Cygwin method to simulate the cases.
I trying to run the executable 'executeOpenfastRegressionCase.py ' with Python3.
when I am entering all the required arguments, I am getting an error as the attached  screenshot.

How do I solve this? Any help is appreciated 👍 
Thanks!
![Anmerkung 2020-07-23 140621](https://user-images.githubusercontent.com/66112322/88284486-c7d28700-cced-11ea-9b6d-24cf1d57e9a3.png)

**Comment by rafmudaf** [comment]
I think you need the other slash in Cygwin (try `/` instead of `\`).

**Comment by TiasaGhosh** [comment]
Hi rafmudaf,
thank you for the response. It worked actually. :) 
But I ran into some other issue now :/ 
![image](https://user-images.githubusercontent.com/66112322/88373917-fbb6b680-cd98-11ea-95e9-e83840ce58b3.png)

am I missing something? 
Thanks again! :)

**Comment by rafmudaf** [comment]
I think you're trying to run the Windows binary on Cygwin. Its subtle, but the Cygwin environment is not the same as a Windows. I dont think the binaries that we distribute through GitHub will run in Cygwin.

If you dont need to modify the source code, you could run the regression tests in Windows command prompt or PowerShell with the binaries from GitHub.
If you _do_ need to modify the code or otherwise need to run in Cygwin, you'll have to compile it from scratch there. See the documentation on [compiling or linux with cmake](https://openfast.readthedocs.io/en/master/source/install/index.html#cmake-with-make-for-linux-macos).
Alternatively, if you want linux on Windows, I highly recommend using the Windows Subsystem for Linux.
