### ISSUE TITLE
FAST Error: invalid logical input when I use Turbsim file for the wind flow  

### ISSUE THREAD

**Issue by Zakarneh0** [OpenFAST/r-test#91]
Am trying to implement a TurbSim file into Fast but it keeps giving me the error 
<img width="665" alt="image" src="https://user-images.githubusercontent.com/126446129/221490788-57afffb7-aa37-4d1b-88f5-b81b902913fd.png">

Can Anyone Help ?

**Comment by bjonkman** [comment]
Please note that TurbSim acts more a s a _preprocessor_ to OpenFAST. After you run the TurbSim executable with a TurbSim input file, it generates wind files. Those files generated by TurbSim can then be read into InflowWind, using options in the InflowWind input file. Based on the error message you shared, it looks like you are trying to have InflowWind read a TurbSim file instead of an InflowWind input file.
